import { runQuestionSeed } from './lib/seedQuestions';
import { practiceBanks } from './data/practiceMaths';

/**
 * Publishes the practice bank: 150 Mathematics questions for every class from 3 to 12 (2026-10-10).
 *
 *   npm run seed:practice                 # report only, writes nothing
 *   npm run seed:practice -- --write      # actually publish
 *
 * Run it from inside `backend/`. Safe to run again: a question already in the bank for its class
 * (same text) is skipped, so a second run publishes nothing new. The questions are generated by
 * `data/practiceMaths.ts`, every answer computed from the numbers in its question, and each one is
 * validated with the API's own rules before anything is written (`lib/seedQuestions.ts`).
 */
void runQuestionSeed({
  script: 'seed-practice.ts',
  label: 'seed-practice',
  classes: practiceBanks(),
  argv: process.argv,
});
